/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 Vanilla.glb --transform --typescript
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Vanilla-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle030.geometry}
        material={materials["Stylized Tree Truck"]}
        position={[0.031, 1.322, -0.055]}
        rotation={[0.003, 0.651, -3.13]}
        scale={[0.073, 0.073, 0.04]}
      />
      <mesh
        geometry={nodes.Circle035.geometry}
        material={materials["Sisal Rope"]}
        position={[0.031, 1.322, -0.055]}
        rotation={[0.003, 0.651, -3.13]}
        scale={[0.073, 0.073, 0.04]}
      />
    </group>
  );
}

useGLTF.preload("/Vanilla-transformed.glb");
